//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace RIPP.App.Test.model
{
    [DataContract(IsReference = true)]
    public partial class OilTableRow: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“ID”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _iD;
    
        [DataMember]
        public int oilTableTypeID
        {
            get { return _oilTableTypeID; }
            set
            {
                if (_oilTableTypeID != value)
                {
                    _oilTableTypeID = value;
                    OnPropertyChanged("oilTableTypeID");
                }
            }
        }
        private int _oilTableTypeID;
    
        [DataMember]
        public int itemOrder
        {
            get { return _itemOrder; }
            set
            {
                if (_itemOrder != value)
                {
                    _itemOrder = value;
                    OnPropertyChanged("itemOrder");
                }
            }
        }
        private int _itemOrder;
    
        [DataMember]
        public string itemName
        {
            get { return _itemName; }
            set
            {
                if (_itemName != value)
                {
                    _itemName = value;
                    OnPropertyChanged("itemName");
                }
            }
        }
        private string _itemName;
    
        [DataMember]
        public string itemEnName
        {
            get { return _itemEnName; }
            set
            {
                if (_itemEnName != value)
                {
                    _itemEnName = value;
                    OnPropertyChanged("itemEnName");
                }
            }
        }
        private string _itemEnName;
    
        [DataMember]
        public string itemUnit
        {
            get { return _itemUnit; }
            set
            {
                if (_itemUnit != value)
                {
                    _itemUnit = value;
                    OnPropertyChanged("itemUnit");
                }
            }
        }
        private string _itemUnit;
    
        [DataMember]
        public string itemCode
        {
            get { return _itemCode; }
            set
            {
                if (_itemCode != value)
                {
                    _itemCode = value;
                    OnPropertyChanged("itemCode");
                }
            }
        }
        private string _itemCode;
    
        [DataMember]
        public string dataType
        {
            get { return _dataType; }
            set
            {
                if (_dataType != value)
                {
                    _dataType = value;
                    OnPropertyChanged("dataType");
                }
            }
        }
        private string _dataType;
    
        [DataMember]
        public Nullable<int> decNumber
        {
            get { return _decNumber; }
            set
            {
                if (_decNumber != value)
                {
                    _decNumber = value;
                    OnPropertyChanged("decNumber");
                }
            }
        }
        private Nullable<int> _decNumber;
    
        [DataMember]
        public Nullable<int> valDigital
        {
            get { return _valDigital; }
            set
            {
                if (_valDigital != value)
                {
                    _valDigital = value;
                    OnPropertyChanged("valDigital");
                }
            }
        }
        private Nullable<int> _valDigital;
    
        [DataMember]
        public Nullable<bool> isKey
        {
            get { return _isKey; }
            set
            {
                if (_isKey != value)
                {
                    _isKey = value;
                    OnPropertyChanged("isKey");
                }
            }
        }
        private Nullable<bool> _isKey;
    
        [DataMember]
        public Nullable<bool> isDisplay
        {
            get { return _isDisplay; }
            set
            {
                if (_isDisplay != value)
                {
                    _isDisplay = value;
                    OnPropertyChanged("isDisplay");
                }
            }
        }
        private Nullable<bool> _isDisplay;
    
        [DataMember]
        public Nullable<double> errDownLimit
        {
            get { return _errDownLimit; }
            set
            {
                if (_errDownLimit != value)
                {
                    _errDownLimit = value;
                    OnPropertyChanged("errDownLimit");
                }
            }
        }
        private Nullable<double> _errDownLimit;
    
        [DataMember]
        public Nullable<double> errUpLimit
        {
            get { return _errUpLimit; }
            set
            {
                if (_errUpLimit != value)
                {
                    _errUpLimit = value;
                    OnPropertyChanged("errUpLimit");
                }
            }
        }
        private Nullable<double> _errUpLimit;
    
        [DataMember]
        public Nullable<double> alertDownLimit
        {
            get { return _alertDownLimit; }
            set
            {
                if (_alertDownLimit != value)
                {
                    _alertDownLimit = value;
                    OnPropertyChanged("alertDownLimit");
                }
            }
        }
        private Nullable<double> _alertDownLimit;
    
        [DataMember]
        public Nullable<double> alertUpLimit
        {
            get { return _alertUpLimit; }
            set
            {
                if (_alertUpLimit != value)
                {
                    _alertUpLimit = value;
                    OnPropertyChanged("alertUpLimit");
                }
            }
        }
        private Nullable<double> _alertUpLimit;
    
        [DataMember]
        public Nullable<double> evalDownLimit
        {
            get { return _evalDownLimit; }
            set
            {
                if (_evalDownLimit != value)
                {
                    _evalDownLimit = value;
                    OnPropertyChanged("evalDownLimit");
                }
            }
        }
        private Nullable<double> _evalDownLimit;
    
        [DataMember]
        public Nullable<double> evalUpLimit
        {
            get { return _evalUpLimit; }
            set
            {
                if (_evalUpLimit != value)
                {
                    _evalUpLimit = value;
                    OnPropertyChanged("evalUpLimit");
                }
            }
        }
        private Nullable<double> _evalUpLimit;
    
        [DataMember]
        public string descript
        {
            get { return _descript; }
            set
            {
                if (_descript != value)
                {
                    _descript = value;
                    OnPropertyChanged("descript");
                }
            }
        }
        private string _descript;
    
        [DataMember]
        public string subItemName
        {
            get { return _subItemName; }
            set
            {
                if (_subItemName != value)
                {
                    _subItemName = value;
                    OnPropertyChanged("subItemName");
                }
            }
        }
        private string _subItemName;
    
        [DataMember]
        public Nullable<bool> isSystem
        {
            get { return _isSystem; }
            set
            {
                if (_isSystem != value)
                {
                    _isSystem = value;
                    OnPropertyChanged("isSystem");
                }
            }
        }
        private Nullable<bool> _isSystem;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion
    }
}
