//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace RIPP.App.AnalCenter.Busi
{
    [DataContract(IsReference = true)]
    public partial class YDResult: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“ID”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _iD;
    
        [DataMember]
        public System.DateTime ADDDATE
        {
            get { return _aDDDATE; }
            set
            {
                if (_aDDDATE != value)
                {
                    _aDDDATE = value;
                    OnPropertyChanged("ADDDATE");
                }
            }
        }
        private System.DateTime _aDDDATE;
    
        [DataMember]
        public string DESCRIPTION
        {
            get { return _dESCRIPTION; }
            set
            {
                if (_dESCRIPTION != value)
                {
                    _dESCRIPTION = value;
                    OnPropertyChanged("DESCRIPTION");
                }
            }
        }
        private string _dESCRIPTION;
    
        [DataMember]
        public System.DateTime SAMPLEDATE
        {
            get { return _sAMPLEDATE; }
            set
            {
                if (_sAMPLEDATE != value)
                {
                    _sAMPLEDATE = value;
                    OnPropertyChanged("SAMPLEDATE");
                }
            }
        }
        private System.DateTime _sAMPLEDATE;
    
        [DataMember]
        public string SAMPLING_POINT
        {
            get { return _sAMPLING_POINT; }
            set
            {
                if (_sAMPLING_POINT != value)
                {
                    _sAMPLING_POINT = value;
                    OnPropertyChanged("SAMPLING_POINT");
                }
            }
        }
        private string _sAMPLING_POINT;
    
        [DataMember]
        public int SAMPLEID
        {
            get { return _sAMPLEID; }
            set
            {
                if (_sAMPLEID != value)
                {
                    _sAMPLEID = value;
                    OnPropertyChanged("SAMPLEID");
                }
            }
        }
        private int _sAMPLEID;
    
        [DataMember]
        public int LMISID
        {
            get { return _lMISID; }
            set
            {
                if (_lMISID != value)
                {
                    _lMISID = value;
                    OnPropertyChanged("LMISID");
                }
            }
        }
        private int _lMISID;
    
        [DataMember]
        public Nullable<double> YD_VALUE1
        {
            get { return _yD_VALUE1; }
            set
            {
                if (_yD_VALUE1 != value)
                {
                    _yD_VALUE1 = value;
                    OnPropertyChanged("YD_VALUE1");
                }
            }
        }
        private Nullable<double> _yD_VALUE1;
    
        [DataMember]
        public Nullable<double> YD_VALUE2
        {
            get { return _yD_VALUE2; }
            set
            {
                if (_yD_VALUE2 != value)
                {
                    _yD_VALUE2 = value;
                    OnPropertyChanged("YD_VALUE2");
                }
            }
        }
        private Nullable<double> _yD_VALUE2;
    
        [DataMember]
        public Nullable<double> YD_VALUE3
        {
            get { return _yD_VALUE3; }
            set
            {
                if (_yD_VALUE3 != value)
                {
                    _yD_VALUE3 = value;
                    OnPropertyChanged("YD_VALUE3");
                }
            }
        }
        private Nullable<double> _yD_VALUE3;
    
        [DataMember]
        public Nullable<double> YD_VALUE4
        {
            get { return _yD_VALUE4; }
            set
            {
                if (_yD_VALUE4 != value)
                {
                    _yD_VALUE4 = value;
                    OnPropertyChanged("YD_VALUE4");
                }
            }
        }
        private Nullable<double> _yD_VALUE4;
    
        [DataMember]
        public Nullable<double> YD_VALUE5
        {
            get { return _yD_VALUE5; }
            set
            {
                if (_yD_VALUE5 != value)
                {
                    _yD_VALUE5 = value;
                    OnPropertyChanged("YD_VALUE5");
                }
            }
        }
        private Nullable<double> _yD_VALUE5;
    
        [DataMember]
        public Nullable<double> YD_VALUE6
        {
            get { return _yD_VALUE6; }
            set
            {
                if (_yD_VALUE6 != value)
                {
                    _yD_VALUE6 = value;
                    OnPropertyChanged("YD_VALUE6");
                }
            }
        }
        private Nullable<double> _yD_VALUE6;
    
        [DataMember]
        public Nullable<double> YD_VALUE7
        {
            get { return _yD_VALUE7; }
            set
            {
                if (_yD_VALUE7 != value)
                {
                    _yD_VALUE7 = value;
                    OnPropertyChanged("YD_VALUE7");
                }
            }
        }
        private Nullable<double> _yD_VALUE7;
    
        [DataMember]
        public Nullable<double> YD_VALUE8
        {
            get { return _yD_VALUE8; }
            set
            {
                if (_yD_VALUE8 != value)
                {
                    _yD_VALUE8 = value;
                    OnPropertyChanged("YD_VALUE8");
                }
            }
        }
        private Nullable<double> _yD_VALUE8;
    
        [DataMember]
        public Nullable<double> YD_VALUE9
        {
            get { return _yD_VALUE9; }
            set
            {
                if (_yD_VALUE9 != value)
                {
                    _yD_VALUE9 = value;
                    OnPropertyChanged("YD_VALUE9");
                }
            }
        }
        private Nullable<double> _yD_VALUE9;
    
        [DataMember]
        public Nullable<double> YD_VALUE10
        {
            get { return _yD_VALUE10; }
            set
            {
                if (_yD_VALUE10 != value)
                {
                    _yD_VALUE10 = value;
                    OnPropertyChanged("YD_VALUE10");
                }
            }
        }
        private Nullable<double> _yD_VALUE10;
    
        [DataMember]
        public Nullable<double> YD_VALUE11
        {
            get { return _yD_VALUE11; }
            set
            {
                if (_yD_VALUE11 != value)
                {
                    _yD_VALUE11 = value;
                    OnPropertyChanged("YD_VALUE11");
                }
            }
        }
        private Nullable<double> _yD_VALUE11;
    
        [DataMember]
        public Nullable<double> YD_VALUE12
        {
            get { return _yD_VALUE12; }
            set
            {
                if (_yD_VALUE12 != value)
                {
                    _yD_VALUE12 = value;
                    OnPropertyChanged("YD_VALUE12");
                }
            }
        }
        private Nullable<double> _yD_VALUE12;
    
        [DataMember]
        public Nullable<double> YD_VALUE13
        {
            get { return _yD_VALUE13; }
            set
            {
                if (_yD_VALUE13 != value)
                {
                    _yD_VALUE13 = value;
                    OnPropertyChanged("YD_VALUE13");
                }
            }
        }
        private Nullable<double> _yD_VALUE13;
    
        [DataMember]
        public Nullable<double> YD_VALUE14
        {
            get { return _yD_VALUE14; }
            set
            {
                if (_yD_VALUE14 != value)
                {
                    _yD_VALUE14 = value;
                    OnPropertyChanged("YD_VALUE14");
                }
            }
        }
        private Nullable<double> _yD_VALUE14;
    
        [DataMember]
        public Nullable<double> YD_VALUE15
        {
            get { return _yD_VALUE15; }
            set
            {
                if (_yD_VALUE15 != value)
                {
                    _yD_VALUE15 = value;
                    OnPropertyChanged("YD_VALUE15");
                }
            }
        }
        private Nullable<double> _yD_VALUE15;
    
        [DataMember]
        public Nullable<double> YD_VALUE16
        {
            get { return _yD_VALUE16; }
            set
            {
                if (_yD_VALUE16 != value)
                {
                    _yD_VALUE16 = value;
                    OnPropertyChanged("YD_VALUE16");
                }
            }
        }
        private Nullable<double> _yD_VALUE16;
    
        [DataMember]
        public Nullable<double> YD_VALUE17
        {
            get { return _yD_VALUE17; }
            set
            {
                if (_yD_VALUE17 != value)
                {
                    _yD_VALUE17 = value;
                    OnPropertyChanged("YD_VALUE17");
                }
            }
        }
        private Nullable<double> _yD_VALUE17;
    
        [DataMember]
        public Nullable<double> YD_VALUE18
        {
            get { return _yD_VALUE18; }
            set
            {
                if (_yD_VALUE18 != value)
                {
                    _yD_VALUE18 = value;
                    OnPropertyChanged("YD_VALUE18");
                }
            }
        }
        private Nullable<double> _yD_VALUE18;
    
        [DataMember]
        public Nullable<double> YD_VALUE19
        {
            get { return _yD_VALUE19; }
            set
            {
                if (_yD_VALUE19 != value)
                {
                    _yD_VALUE19 = value;
                    OnPropertyChanged("YD_VALUE19");
                }
            }
        }
        private Nullable<double> _yD_VALUE19;
    
        [DataMember]
        public Nullable<double> YD_VALUE20
        {
            get { return _yD_VALUE20; }
            set
            {
                if (_yD_VALUE20 != value)
                {
                    _yD_VALUE20 = value;
                    OnPropertyChanged("YD_VALUE20");
                }
            }
        }
        private Nullable<double> _yD_VALUE20;
    
        [DataMember]
        public Nullable<double> YD_VALUE21
        {
            get { return _yD_VALUE21; }
            set
            {
                if (_yD_VALUE21 != value)
                {
                    _yD_VALUE21 = value;
                    OnPropertyChanged("YD_VALUE21");
                }
            }
        }
        private Nullable<double> _yD_VALUE21;
    
        [DataMember]
        public Nullable<double> YD_VALUE22
        {
            get { return _yD_VALUE22; }
            set
            {
                if (_yD_VALUE22 != value)
                {
                    _yD_VALUE22 = value;
                    OnPropertyChanged("YD_VALUE22");
                }
            }
        }
        private Nullable<double> _yD_VALUE22;
    
        [DataMember]
        public Nullable<double> YD_VALUE23
        {
            get { return _yD_VALUE23; }
            set
            {
                if (_yD_VALUE23 != value)
                {
                    _yD_VALUE23 = value;
                    OnPropertyChanged("YD_VALUE23");
                }
            }
        }
        private Nullable<double> _yD_VALUE23;
    
        [DataMember]
        public Nullable<double> YD_VALUE24
        {
            get { return _yD_VALUE24; }
            set
            {
                if (_yD_VALUE24 != value)
                {
                    _yD_VALUE24 = value;
                    OnPropertyChanged("YD_VALUE24");
                }
            }
        }
        private Nullable<double> _yD_VALUE24;
    
        [DataMember]
        public Nullable<double> YD_VALUE25
        {
            get { return _yD_VALUE25; }
            set
            {
                if (_yD_VALUE25 != value)
                {
                    _yD_VALUE25 = value;
                    OnPropertyChanged("YD_VALUE25");
                }
            }
        }
        private Nullable<double> _yD_VALUE25;
    
        [DataMember]
        public Nullable<double> YD_VALUE26
        {
            get { return _yD_VALUE26; }
            set
            {
                if (_yD_VALUE26 != value)
                {
                    _yD_VALUE26 = value;
                    OnPropertyChanged("YD_VALUE26");
                }
            }
        }
        private Nullable<double> _yD_VALUE26;
    
        [DataMember]
        public Nullable<double> YD_VALUE27
        {
            get { return _yD_VALUE27; }
            set
            {
                if (_yD_VALUE27 != value)
                {
                    _yD_VALUE27 = value;
                    OnPropertyChanged("YD_VALUE27");
                }
            }
        }
        private Nullable<double> _yD_VALUE27;
    
        [DataMember]
        public Nullable<double> YD_VALUE28
        {
            get { return _yD_VALUE28; }
            set
            {
                if (_yD_VALUE28 != value)
                {
                    _yD_VALUE28 = value;
                    OnPropertyChanged("YD_VALUE28");
                }
            }
        }
        private Nullable<double> _yD_VALUE28;
    
        [DataMember]
        public Nullable<double> YD_VALUE29
        {
            get { return _yD_VALUE29; }
            set
            {
                if (_yD_VALUE29 != value)
                {
                    _yD_VALUE29 = value;
                    OnPropertyChanged("YD_VALUE29");
                }
            }
        }
        private Nullable<double> _yD_VALUE29;
    
        [DataMember]
        public Nullable<double> YD_VALUE30
        {
            get { return _yD_VALUE30; }
            set
            {
                if (_yD_VALUE30 != value)
                {
                    _yD_VALUE30 = value;
                    OnPropertyChanged("YD_VALUE30");
                }
            }
        }
        private Nullable<double> _yD_VALUE30;
    
        [DataMember]
        public Nullable<double> YD_VALUE31
        {
            get { return _yD_VALUE31; }
            set
            {
                if (_yD_VALUE31 != value)
                {
                    _yD_VALUE31 = value;
                    OnPropertyChanged("YD_VALUE31");
                }
            }
        }
        private Nullable<double> _yD_VALUE31;
    
        [DataMember]
        public Nullable<double> YD_VALUE32
        {
            get { return _yD_VALUE32; }
            set
            {
                if (_yD_VALUE32 != value)
                {
                    _yD_VALUE32 = value;
                    OnPropertyChanged("YD_VALUE32");
                }
            }
        }
        private Nullable<double> _yD_VALUE32;
    
        [DataMember]
        public Nullable<double> YD_VALUE33
        {
            get { return _yD_VALUE33; }
            set
            {
                if (_yD_VALUE33 != value)
                {
                    _yD_VALUE33 = value;
                    OnPropertyChanged("YD_VALUE33");
                }
            }
        }
        private Nullable<double> _yD_VALUE33;
    
        [DataMember]
        public Nullable<double> YD_VALUE34
        {
            get { return _yD_VALUE34; }
            set
            {
                if (_yD_VALUE34 != value)
                {
                    _yD_VALUE34 = value;
                    OnPropertyChanged("YD_VALUE34");
                }
            }
        }
        private Nullable<double> _yD_VALUE34;
    
        [DataMember]
        public Nullable<double> YD_VALUE35
        {
            get { return _yD_VALUE35; }
            set
            {
                if (_yD_VALUE35 != value)
                {
                    _yD_VALUE35 = value;
                    OnPropertyChanged("YD_VALUE35");
                }
            }
        }
        private Nullable<double> _yD_VALUE35;
    
        [DataMember]
        public Nullable<double> YD_VALUE36
        {
            get { return _yD_VALUE36; }
            set
            {
                if (_yD_VALUE36 != value)
                {
                    _yD_VALUE36 = value;
                    OnPropertyChanged("YD_VALUE36");
                }
            }
        }
        private Nullable<double> _yD_VALUE36;
    
        [DataMember]
        public Nullable<double> YD_VALUE37
        {
            get { return _yD_VALUE37; }
            set
            {
                if (_yD_VALUE37 != value)
                {
                    _yD_VALUE37 = value;
                    OnPropertyChanged("YD_VALUE37");
                }
            }
        }
        private Nullable<double> _yD_VALUE37;
    
        [DataMember]
        public Nullable<double> YD_VALUE38
        {
            get { return _yD_VALUE38; }
            set
            {
                if (_yD_VALUE38 != value)
                {
                    _yD_VALUE38 = value;
                    OnPropertyChanged("YD_VALUE38");
                }
            }
        }
        private Nullable<double> _yD_VALUE38;
    
        [DataMember]
        public Nullable<double> YD_VALUE39
        {
            get { return _yD_VALUE39; }
            set
            {
                if (_yD_VALUE39 != value)
                {
                    _yD_VALUE39 = value;
                    OnPropertyChanged("YD_VALUE39");
                }
            }
        }
        private Nullable<double> _yD_VALUE39;
    
        [DataMember]
        public Nullable<double> YD_VALUE40
        {
            get { return _yD_VALUE40; }
            set
            {
                if (_yD_VALUE40 != value)
                {
                    _yD_VALUE40 = value;
                    OnPropertyChanged("YD_VALUE40");
                }
            }
        }
        private Nullable<double> _yD_VALUE40;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
