//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIPP.Web.Chem.Datas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RIPPWebEntities : DbContext
    {
        public RIPPWebEntities()
            : base("name=RIPPWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<model> model { get; set; }
        public DbSet<results> results { get; set; }
        public DbSet<S_FindPWD> S_FindPWD { get; set; }
        public DbSet<S_Group> S_Group { get; set; }
        public DbSet<S_User> S_User { get; set; }
        public DbSet<S_UserInRole> S_UserInRole { get; set; }
        public DbSet<spec> spec { get; set; }
    }
}
