//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIPP.Web.Chem.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class model
    {
        public int id { get; set; }
        public int uid { get; set; }
        public System.DateTime addtime { get; set; }
        public string name { get; set; }
        public string path { get; set; }
        public int type { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public int gid { get; set; }
    }
}
