//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIPP.Web.Chem.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_FindPWD
    {
        public int id { get; set; }
        public int uid { get; set; }
        public string Email { get; set; }
        public string Secret { get; set; }
        public string Guid { get; set; }
        public System.DateTime SubmitDate { get; set; }
    }
}
