//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIPP.Web.Chem.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Group
    {
        public int ID { get; set; }
        public string Names { get; set; }
        public int MasterUserID { get; set; }
        public string Remark { get; set; }
        public bool Deleted { get; set; }
    }
}
